import { createContext, useContext, useState, type ReactNode } from "react";

export type Lang = "en" | "zh" | "es" | "fr" | "pt" | "vi";
export type Dialect = string | null;

const LANGUAGE_FAMILIES = {
  en: { name: "English", dialects: [] },
  zh: { name: "Chinese", dialects: ["mandarin", "cantonese", "fujian", "shanghai"] },
  es: { name: "Spanish", dialects: ["latin_american", "castilian"] },
  fr: { name: "French", dialects: [] },
  pt: { name: "Portuguese", dialects: [] },
  vi: { name: "Vietnamese", dialects: [] },
};

export const translations = {
  en: {
    nav: {
      platform: "Platform", howItWorks: "How It Works", pricing: "Pricing",
      login: "Log in", getStarted: "Get Started",
    },
    hero: {
      badge: "AI Hiring Help",
      headline1: "Hire people you", headline2: "can actually", trust: "trust.",
      subtext: "For immigrant restaurant owners. Workers checked. Simple hiring.",
      ctaPost: "Post a Job", ctaFind: "Find Work",
    },
    metrics: {
      languages: { value: "6 Languages", label: "Supported", desc: "Post jobs and find workers in Spanish, Mandarin, French, Portuguese, Vietnamese, and English." },
      aiVerified: { value: "AI Checked", label: "Workers", desc: "Every person is checked and gets a match score before you see them." },
      jobPost: { value: "60 Second", label: "Job Posts", desc: "Describe the job in any language. AI makes your listing in one minute." },
    },
    features: {
      sectionLabel: "Why ENTR", sectionHeading: "Made for how restaurants really hire.",
      aiScreening: { label: "AI Screening", heading: "See the best fit first.", body: "Every job application gets a match score. You see the best matches first, not the newest ones.", chips: [] },
      languages: { label: "6 Languages", heading: "No language getting in your way.", body: "Workers apply in their language. You read it in yours. Simple. Clear.", chips: ["English","Español","中文","Français","Português","Tiếng Việt"] },
      verification: { label: "Worker Check", heading: "Know who you're hiring.", body: "We check ID documents and compare faces. You know exactly who is walking in your door.", checks: [] },
      cards: {
        aiScreening: {
          header: "People Who Applied", badge: "AI Ranked", footer: "3 of 18 people shown", viewAll: "See more →",
          candidates: [
            { name: "Maria G.",   role: "Line Cook · 3 yrs", score: 87 },
            { name: "Carlos R.",  role: "Prep Cook · 1 yr",  score: 64 },
            { name: "Jae-won L.", role: "Line Cook · 6 mo",  score: 31 },
          ],
        },
        language: {
          header: "Job Language", subheader: "Pick a language to see how it looks",
          previewLabel: "中文 Example",
          previewText: "招聘经验丰富的炒锅厨师，负责晚间服务。每周发薪，提供餐饮福利。",
          autoTranslated: "Translated from English",
        },
        verification: {
          header: "ID Check", badge: "Checked",
          workerName: "Anh Tran", workerRole: "Server · Ho Chi Minh City",
          identityVerified: "ID Checked and Approved",
          checks: ["Real government ID", "Face match 97%", "Valid until 2028"],
        },
      },
    },
    howItWorks: {
      label: "How It Works", heading: "Hire in three steps.",
      steps: [
        { number: "01", heading: "Post a job", body: "Tell us the job, pay, and hours. Takes about 60 seconds." },
        { number: "02", heading: "Workers apply", body: "Good people from your area apply in their own language." },
        { number: "03", heading: "AI matches them", body: "Every application gets a score and is checked before you see it." },
      ],
      cta: "Get Started Free",
    },
    pricing: {
      label: "Pricing",
      heading: "Simple pricing.",
      subtext: "Start free. Pay as you grow. No surprises.",
      badge: "Most Popular",
      plans: [
        {
          name: "Free",
          price: "$0",
          features: [
            { text: "1 job listing", included: true },
            { text: "All 6 languages", included: true },
            { text: "See who applied", included: true },
            { text: "Match scores", included: false },
            { text: "Worker check", included: false },
            { text: "Fast help", included: false },
            { text: "Reports", included: false },
          ],
          cta: "Start free",
        },
        {
          name: "Starter",
          price: "$19",
          features: [
            { text: "3 job listings", included: true },
            { text: "All 6 languages", included: true },
            { text: "Match scores", included: true },
            { text: "See who applied", included: true },
            { text: "Worker check", included: true },
            { text: "Fast help", included: false },
            { text: "Reports", included: false },
          ],
          cta: "Get started",
        },
        {
          name: "Pro",
          price: "$39",
          features: [
            { text: "Unlimited listings", included: true },
            { text: "All 6 languages", included: true },
            { text: "Match scores", included: true },
            { text: "Full check reports", included: true },
            { text: "Fast help", included: true },
            { text: "See who applied", included: true },
            { text: "Reports", included: false },
          ],
          cta: "Start with Pro",
        },
        {
          name: "Business",
          price: "$79",
          features: [
            { text: "Everything in Pro", included: true },
            { text: "Multiple restaurants", included: true },
            { text: "Team access", included: true },
            { text: "Reports", included: true },
            { text: "All 6 languages", included: true },
            { text: "Full check reports", included: true },
            { text: "Fast help", included: true },
          ],
          cta: "Contact sales",
        },
      ],
      perMonth: "/month",
    },
    featureExplanations: {
      title: "What's in each plan",
      subtitle: "See what each feature does and how it helps you hire",
      features: {
        "1 active listing": {
          heading: "1 Job Listing",
          description: "Post one job at a time. Good for filling one spot. Once you fill it or close it, post a new one.",
          isPaidFeature: false,
        },
        "3 active listings": {
          heading: "3 Job Listings",
          description: "Post 3 jobs at once. Good for busy restaurants that need to hire multiple people.",
          isPaidFeature: false,
        },
        "Unlimited listings": {
          heading: "Unlimited Listings",
          description: "Post as many jobs as you need. Post whenever, as much as you want.",
          isPaidFeature: false,
        },
        "All 6 languages": {
          heading: "All 6 Languages",
          description: "Post in English, Spanish, Mandarin, French, Portuguese, or Vietnamese. Workers apply in their language. You see it all translated.",
          isPaidFeature: false,
        },
        "Match scores": {
          heading: "Match Scores",
          description: "AI reads each application and ranks people by how well they fit. See the best matches first, not the newest ones. Saves hours of reading bad applications.",
          isPaidFeature: true,
        },
        "See who applied": {
          heading: "See Who Applied",
          description: "One simple list of everyone who applied. You see their name, contact info, and their message. Easy to call or text them.",
          isPaidFeature: false,
        },
        "Worker check": {
          heading: "Worker Check",
          description: "Workers send their ID and a selfie. AI checks both. You see a badge showing they've been checked. Hire with confidence.",
          isPaidFeature: true,
        },
        "Full check reports": {
          heading: "Full Check Reports",
          description: "See all the details about the check: face match score, age, ID real or fake. You know everything about the worker.",
          isPaidFeature: true,
        },
        "Fast help": {
          heading: "Fast Help",
          description: "Get answers quickly when you need help. We reply in hours, not days. Your hiring keeps moving.",
          isPaidFeature: true,
        },
        "Reports": {
          heading: "Reports",
          description: "Charts showing which jobs get interest, how many applied, trends. See what's working. Make smarter hiring choices.",
          isPaidFeature: true,
        },
        "Multiple restaurants": {
          heading: "Multiple Restaurants",
          description: "Post jobs for many restaurants. See all applications in one place. One login. Easy switching between restaurants.",
          isPaidFeature: true,
        },
        "Team access": {
          heading: "Team Access",
          description: "Your managers and staff can help with hiring. One system for everyone. No multiple logins. No endless forwarding.",
          isPaidFeature: true,
        },
        "Everything in Pro": {
          heading: "Everything in Pro",
          description: "Business gets everything in Pro: unlimited jobs, match scores, full checks, fast help, reports. Plus multiple restaurants and team access.",
          isPaidFeature: false,
        },
      },
    },
    tech: {
      label: "Built with",
      items: [
        { name: "Claude AI", desc: "Matching & translation" },
        { name: "React",     desc: "App interface" },
        { name: "Flask",     desc: "Backend" },
        { name: "PostgreSQL",desc: "Database" },
        { name: "AWS",       desc: "Servers" },
        { name: "Stripe",    desc: "Payments" },
      ],
    },
    chat: {
      title: "ENTR Help", subtitle: "Ask anything",
      placeholder: "Ask a question…",
      welcome: "Hi! I'm here to help you hire workers. Questions about jobs, languages, or costs? Ask me.",
      suggestions: ["How does matching work?", "What languages do you support?", "How much does it cost?"],
      responses: {
        screening: "AI reads each application and scores it 0 to 100 based on your needs. Best matches appear first. No more scrolling through bad fits.",
        languages: "We support English, Spanish, Mandarin, French, Portuguese, and Vietnamese. Workers apply in their language. You see everything translated.",
        pricing: "Start free with 1 job listing. Most people pick Pro for $39 per month. Unlimited jobs, matching, and worker checks.",
        default: "ENTR helps you find and hire great workers fast. We check their ID, match them to your jobs, and translate everything. What would you like to know?",
      },
    },
    footer: {
      tagline: "AI hiring made simple for immigrant restaurant owners.",
      columns: { product: "Product", support: "Help", company: "About", languages: "Languages" },
    },

    // ── Authenticated UI ───────────────────────────────────────────────────────
    layout: {
      dashboard: "Dashboard", postJob: "Post Job", browseJobs: "Find Jobs",
      verification: "ID Check", logout: "Log out",
      langToggle: "中文",
    },
    auth: {
      welcomeBack: "Welcome back", signInTitle: "Log in",
      email: "Email", password: "Password",
      signIn: "Log in", signingIn: "Logging in…",
      noAccount: "No account yet?", signUpLink: "Sign up",
      getStartedFree: "Get started free", createAccountTitle: "Create account",
      iAmA: "I am a…", restaurantOwner: "Restaurant Owner", jobSeeker: "Job Seeker",
      fullName: "Your Name", restaurantName: "Restaurant Name",
      preferredLanguage: "Preferred Language",
      createAccount: "Create account", creatingAccount: "Creating account…",
      alreadyHaveAccount: "Have an account?", signInLink: "Log in",
    },
    employerDash: {
      label: "Restaurant Dashboard", welcome: "Welcome,",
      totalJobs: "Total Jobs", activeJobs: "Active Now", totalApplications: "Total Applications",
      yourJobPostings: "Your Jobs", postJob: "+ Post a Job",
      noJobsYet: "No jobs posted yet.", postFirstJob: "Post your first job",
      loading: "Loading…",
      cols: { title: "Job", location: "Location", pay: "Pay", applications: "Applied", status: "Status", actions: "Action" },
      open: "Open", closed: "Closed",
      viewApps: "See Who Applied", close: "Close", reopen: "Reopen",
    },
    postJob: {
      label: "Restaurant Owner", title: "Post a Job", subtitle: "Tell us about the job and we'll post it.",
      titleField: "Job Title", titlePlaceholder: "Line Cook, Server, Dishwasher",
      description: "Job Details", descPlaceholder: "What work will they do? Any special needs?",
      pay: "Pay", payPlaceholder: "$18/hr or $45k/year",
      hours: "Hours", hoursPlaceholder: "Full-time, 30-40 hours a week",
      experience: "Years of Experience Needed",
      langPref: "Language", langAny: "Any language",
      location: "Location", locationPlaceholder: "San Francisco, CA",
      submit: "Post Job", submitting: "Posting…", cancel: "Cancel",
    },
    applications: {
      backToDash: "← Back", label: "Who Applied",
      sortedByScore: "best matches first",
      application: "person", applicationPlural: "people",
      noApplications: "No applications yet.",
      aiSummary: "AI Summary", coverLetter: "Their Message",
      experience: "Experience", languages: "Languages", faceMatch: "Face Match",
      notScored: "Not scored",
      statuses: { pending: "New", reviewed: "Looked at", accepted: "Hired", rejected: "Passed" },
      verif: { verified: "Checked", flagged: "Issue", pending: "Checking" },
    },
    workerDash: {
      label: "My Jobs", welcome: "Hello,",
      myApplications: "My Applications", browseJobs: "Find Jobs",
      noApplications: "You haven't applied yet.", browseAvailable: "Find jobs",
      aiScore: "Match Score",
      verif: {
        label: "ID Check",
        verified: "Your ID is checked",
        flagged: "ID check failed. Send again.",
        manualReview: "Someone is checking your ID",
        inProgress: "Checking your ID",
        notVerified: "ID not checked yet. Check to unlock jobs.",
        verifyNow: "Check My ID", resubmit: "Send Again",
      },
      appStatuses: { pending: "New", reviewed: "Seen", accepted: "Yes", rejected: "No" },
    },
    browseJobs: {
      label: "Find Jobs", title: "Jobs Available",
      searchPlaceholder: "Search job, restaurant, or location",
      noJobs: "No jobs right now. Check back soon.",
      noMatch: "No jobs match your search.",
      applyNow: "Apply",
      loading: "Loading…",
    },
    applyPage: {
      back: "← Back to Jobs", label: "Apply",
      jobDetails: "Job Info", yourApplication: "Your Application",
      pay: "Pay", hours: "Hours", location: "Where",
      experienceRequired: "Experience Needed", langPref: "Language",
      notSpecified: "Not set", none: "None", any: "Any",
      description: "About the Job",
      coverLetter: "Your Message",
      coverLetterPlaceholder: "Tell them why you're a great fit. Keep it simple and honest.",
      coverLetterNote: "AI will score your application based on how well you match.",
      submit: "Send Application", submitting: "Sending…", cancel: "Cancel",
      jobNotFound: "Job not found or no longer open.",
    },
    verifyPage: {
      label: "Worker", title: "Verify Your ID",
      tagline: "Checked workers get more job offers.",
      stepOf: "Step", of: "of",
      step1: {
        title: "Send Your ID",
        desc: "Upload a clear photo of your ID (passport, driver license, national ID).",
        label: "ID Photo", hint: "JPG or PNG, 10MB max", uploading: "Uploading ID…",
      },
      step2: {
        title: "Take a Selfie",
        desc: "Clear photo of your face. AI will compare it to your ID.",
        label: "Selfie", hint: "JPG or PNG, clear face", uploading: "Checking…",
      },
      upload: { clickOrDrag: "Click or drag to upload", uploading: "Uploading…", selected: "File ready. Click to change." },
      result: {
        verified: "ID Checked", flagged: "Check Failed",
        manualReview: "Someone is reviewing it", pending: "Checking",
        underReview: "Under Review",
        nameOnId: "Name on ID", faceMatchScore: "Face Match",
        ageVerified: "Age OK", ageYes: "Yes (18+)", ageNo: "No / Unknown",
        resubmit: "Send Again", resetting: "Starting over…",
      },
      loading: "Loading…",
    },
  },

  es: {
    nav: {
      platform: "Plataforma", howItWorks: "Cómo funciona", pricing: "Precios",
      login: "Entrar", getStarted: "Empezar",
    },
    hero: {
      badge: "Contratación con IA",
      headline1: "Contrata gente que", headline2: "realmente puedes", trust: "confiar.",
      subtext: "Para dueños de restaurantes inmigrantes. Trabajadores verificados. Sin dudas.",
      ctaPost: "Publicar trabajo", ctaFind: "Buscar trabajo",
    },
    metrics: {
      languages: { value: "6 idiomas", label: "Disponibles", desc: "Publica trabajos y encuentra personas en español, mandarín, francés, portugués, vietnamita e inglés." },
      aiVerified: { value: "Gente", label: "Verificada", desc: "Cada persona es verificada y obtiene una puntuación de compatibilidad antes de que la veas." },
      jobPost: { value: "60 segundos", label: "Para publicar", desc: "Describe el trabajo en cualquier idioma. IA hace tu anuncio en un minuto." },
    },
    features: {
      sectionLabel: "Por qué ENTR", sectionHeading: "Hecho para cómo contratan los restaurantes.",
      aiScreening: { label: "Búsqueda con IA", heading: "Ve las mejores opciones primero.", body: "Cada solicitud obtiene una puntuación de compatibilidad. Ves los mejores primero, no los más recientes.", chips: [] },
      languages: { label: "6 idiomas", heading: "Sin barreras de idioma.", body: "La gente solicita en su idioma. Tú lo lees en el tuyo. Simple. Claro.", chips: ["English","Español","中文","Français","Português","Tiếng Việt"] },
      verification: { label: "Verificación", heading: "Sabe quién estás contratando.", body: "Verificamos la ID y las caras coinciden. Sabes exactamente quién entra a tu puerta.", checks: [] },
      cards: {
        aiScreening: {
          header: "Gente que solicitó", badge: "Clasificada por IA", footer: "3 de 18 personas mostradas", viewAll: "Ver más →",
          candidates: [
            { name: "Maria G.",   role: "Cocinera de línea · 3 años", score: 87 },
            { name: "Carlos R.",  role: "Preparador de alimentos · 1 año",  score: 64 },
            { name: "Jae-won L.", role: "Cocinera de línea · 6 meses", score: 31 },
          ],
        },
        language: {
          header: "Idioma del anuncio", subheader: "Elige un idioma para ver cómo se ve",
          previewLabel: "Ejemplo en español",
          previewText: "Buscamos cocinero de parrilla con experiencia para turno nocturno. Pago semanal, comidas incluidas.",
          autoTranslated: "Traducido del inglés",
        },
        verification: {
          header: "Verificación", badge: "Verificado",
          workerName: "Anh Tran", workerRole: "Camarero · Ho Chi Minh",
          identityVerified: "Verificado",
          checks: ["ID verdadera", "Cara coincide 97%", "Válida hasta 2028"],
        },
      },
    },
    howItWorks: {
      label: "Cómo funciona", heading: "Contrata en tres pasos.",
      steps: [
        { number: "01", heading: "Publica un trabajo", body: "Cuéntanos el trabajo, el pago y las horas. Toma unos 60 segundos." },
        { number: "02", heading: "La gente solicita", body: "Gente buena de tu área solicita en su propio idioma." },
        { number: "03", heading: "IA los compara", body: "Cada solicitud obtiene una puntuación y se verifica antes de que la veas." },
      ],
      cta: "Empezar gratis",
    },
    pricing: {
      label: "Precios",
      heading: "Precios simples.",
      subtext: "Empieza gratis. Paga según crezcas. Sin sorpresas.",
      badge: "Más popular",
      plans: [
        {
          name: "Gratis",
          price: "$0",
          features: [
            { text: "1 anuncio de trabajo", included: true },
            { text: "6 idiomas", included: true },
            { text: "Ver quién solicitó", included: true },
            { text: "Puntuaciones de compatibilidad", included: false },
            { text: "Verificación de trabajadores", included: false },
            { text: "Ayuda rápida", included: false },
            { text: "Reportes", included: false },
          ],
          cta: "Empezar gratis",
        },
        {
          name: "Inicio",
          price: "$19",
          features: [
            { text: "3 anuncios de trabajo", included: true },
            { text: "6 idiomas", included: true },
            { text: "Puntuaciones de compatibilidad", included: true },
            { text: "Ver quién solicitó", included: true },
            { text: "Verificación de trabajadores", included: true },
            { text: "Ayuda rápida", included: false },
            { text: "Reportes", included: false },
          ],
          cta: "Empezar",
        },
        {
          name: "Pro",
          price: "$39",
          features: [
            { text: "Trabajos ilimitados", included: true },
            { text: "6 idiomas", included: true },
            { text: "Puntuaciones de compatibilidad", included: true },
            { text: "Reportes de verificación completos", included: true },
            { text: "Ayuda rápida", included: true },
            { text: "Ver quién solicitó", included: true },
            { text: "Reportes", included: false },
          ],
          cta: "Empezar Pro",
        },
        {
          name: "Negocios",
          price: "$79",
          features: [
            { text: "Todo en Pro", included: true },
            { text: "Múltiples restaurantes", included: true },
            { text: "Acceso de equipo", included: true },
            { text: "Reportes", included: true },
            { text: "6 idiomas", included: true },
            { text: "Reportes de verificación completos", included: true },
            { text: "Ayuda rápida", included: true },
          ],
          cta: "Contacta ventas",
        },
      ],
      perMonth: "/mes",
    },
    featureExplanations: {
      title: "Qué hay en cada plan",
      subtitle: "Ve qué hace cada función y cómo te ayuda a contratar",
      features: {
        "1 active listing": {
          heading: "1 anuncio de trabajo",
          description: "Publica un trabajo a la vez. Bueno para llenar un puesto. Una vez que lo cierres, publica otro.",
          isPaidFeature: false,
        },
        "3 active listings": {
          heading: "3 anuncios de trabajo",
          description: "Publica 3 trabajos al mismo tiempo. Bueno para restaurantes ocupados que contratan varias personas.",
          isPaidFeature: false,
        },
        "Unlimited listings": {
          heading: "Trabajos ilimitados",
          description: "Publica tantos trabajos como necesites. Cuando quieras, tanto como quieras.",
          isPaidFeature: false,
        },
        "All 6 languages": {
          heading: "6 idiomas",
          description: "Publica en español, inglés, mandarín, francés, portugués o vietnamita. La gente solicita en su idioma. Ves todo traducido.",
          isPaidFeature: false,
        },
        "Fit scores": {
          heading: "Puntuaciones de compatibilidad",
          description: "IA lee cada solicitud y la clasifica 0 a 100 según qué tan bien encaja. Ve lo mejor primero, no lo más nuevo. Ahorra horas leyendo solicitudes malas.",
          isPaidFeature: true,
        },
        "Basic applicant list": {
          heading: "Ver quién solicitó",
          description: "Una lista simple de todos los que solicitaron. Ves su nombre, contacto y mensaje. Fácil llamar o mandar mensaje.",
          isPaidFeature: false,
        },
        "Worker verification": {
          heading: "Verificación de trabajadores",
          description: "La gente envía su ID y una selfie. IA verifica ambas. Ves una insignia mostrando que fueron verificados. Contrata con confianza.",
          isPaidFeature: true,
        },
        "Full verification reports": {
          heading: "Reportes de verificación completos",
          description: "Ve todos los detalles: puntuación de cara, edad, ID real o falsa. Sabes todo sobre el trabajador.",
          isPaidFeature: true,
        },
        "Priority support": {
          heading: "Ayuda rápida",
          description: "Obtén respuestas rápido cuando necesites ayuda. Respondemos en horas, no días. Tu contratación sigue adelante.",
          isPaidFeature: true,
        },
        "Analytics dashboard": {
          heading: "Reportes",
          description: "Gráficos mostrando qué trabajos interesan, cuántos solicitan, tendencias. Ve qué funciona. Toma decisiones de contratación más inteligentes.",
          isPaidFeature: true,
        },
        "Multiple locations": {
          heading: "Múltiples restaurantes",
          description: "Publica trabajos para muchos restaurantes. Ve todas las solicitudes en un lugar. Un login. Cambia fácil entre restaurantes.",
          isPaidFeature: true,
        },
        "Team access": {
          heading: "Acceso de equipo",
          description: "Tu gerente y staff pueden ayudar a contratar. Un sistema para todos. Sin múltiples logins. Sin transferencias interminables.",
          isPaidFeature: true,
        },
        "Everything in Pro": {
          heading: "Todo en Pro",
          description: "Negocios obtiene todo en Pro: trabajos ilimitados, puntuaciones, verificación completa, ayuda rápida, reportes. Más múltiples restaurantes y equipo.",
          isPaidFeature: false,
        },
      },
    },
    tech: {
      label: "Construido con",
      items: [
        { name: "Claude IA", desc: "Búsqueda y traducción" },
        { name: "React",     desc: "Interfaz" },
        { name: "Flask",     desc: "Backend" },
        { name: "PostgreSQL",desc: "Base de datos" },
        { name: "AWS",       desc: "Servidores" },
        { name: "Stripe",    desc: "Pagos" },
      ],
    },
    chat: {
      title: "Ayuda ENTR", subtitle: "Pregunta algo",
      placeholder: "Haz una pregunta…",
      welcome: "Hola, estoy aquí para ayudarte a contratar gente. ¿Preguntas sobre trabajos, idiomas o precios? Pregúntame.",
      suggestions: ["¿Cómo funciona la búsqueda?", "¿Qué idiomas usan?", "¿Cuánto cuesta?"],
      responses: {
        screening: "IA lee cada solicitud y la puntúa 0 a 100 según tus necesidades. Lo mejor aparece primero. Sin más desplazarte por malas opciones.",
        languages: "Soportamos español, inglés, mandarín, francés, portugués y vietnamita. La gente solicita en su idioma. Ves todo traducido.",
        pricing: "Empieza gratis con 1 anuncio. La mayoría elige Pro por $39 al mes. Trabajos ilimitados, búsqueda y verificación.",
        default: "ENTR te ayuda encontrar y contratar gente buena rápido. Verificamos IDs, los comparamos con tus trabajos, traducimos todo. ¿Qué quieres saber?",
      },
    },
    footer: {
      tagline: "Contratación con IA hecha simple para dueños de restaurantes inmigrantes.",
      columns: { product: "Producto", support: "Ayuda", company: "Nosotros", languages: "Idiomas" },
    },

    // ── Authenticated UI ───────────────────────────────────────────────────────
    layout: {
      dashboard: "Panel", postJob: "Publicar", browseJobs: "Buscar",
      verification: "Verificación", logout: "Salir",
      langToggle: "中文",
    },
    auth: {
      welcomeBack: "Bienvenido", signInTitle: "Entra a tu cuenta",
      email: "Email", password: "Contraseña",
      signIn: "Entrar", signingIn: "Entrando…",
      noAccount: "¿Sin cuenta?", signUpLink: "Crear",
      getStartedFree: "Empezar gratis", createAccountTitle: "Crear cuenta",
      iAmA: "Soy…", restaurantOwner: "Dueño de restaurante", jobSeeker: "Buscador de trabajo",
      fullName: "Tu nombre", restaurantName: "Nombre del restaurante",
      preferredLanguage: "Idioma preferido",
      createAccount: "Crear cuenta", creatingAccount: "Creando…",
      alreadyHaveAccount: "¿Ya tienes cuenta?", signInLink: "Entrar",
    },
    employerDash: {
      label: "Mi restaurante", welcome: "Bienvenido,",
      totalJobs: "Total de trabajos", activeJobs: "Activos ahora", totalApplications: "Total de solicitudes",
      yourJobPostings: "Mis trabajos", postJob: "+ Publicar",
      noJobsYet: "Sin trabajos publicados.", postFirstJob: "Publica tu primer trabajo",
      loading: "Cargando…",
      cols: { title: "Trabajo", location: "Lugar", pay: "Pago", applications: "Solicitudes", status: "Estado", actions: "Acción" },
      open: "Abierto", closed: "Cerrado",
      viewApps: "Ver solicitudes", close: "Cerrar", reopen: "Reabrir",
    },
    postJob: {
      label: "Dueño", title: "Publica un trabajo", subtitle: "Cuéntanos sobre el trabajo y lo publicamos.",
      titleField: "Tipo de trabajo", titlePlaceholder: "Cocinero, camarero, lavaplatos",
      description: "Detalles", descPlaceholder: "¿Qué van a hacer? ¿Algo especial?",
      pay: "Pago", payPlaceholder: "$18/hora o $45k/año",
      hours: "Horas", hoursPlaceholder: "Tiempo completo, 30-40 horas a la semana",
      experience: "Años de experiencia",
      langPref: "Idioma", langAny: "Cualquier idioma",
      location: "Lugar", locationPlaceholder: "Ciudad, estado",
      submit: "Publicar", submitting: "Publicando…", cancel: "Cancelar",
    },
    applications: {
      backToDash: "← Atrás", label: "Quién solicitó",
      sortedByScore: "mejores primeros",
      application: "persona", applicationPlural: "personas",
      noApplications: "Sin solicitudes.",
      aiSummary: "Resumen IA", coverLetter: "Su mensaje",
      experience: "Experiencia", languages: "Idiomas", faceMatch: "Cara",
      notScored: "Sin puntuación",
      statuses: { pending: "Nuevo", reviewed: "Visto", accepted: "Sí", rejected: "No" },
      verif: { verified: "Verificado", flagged: "Problema", pending: "Verificando" },
    },
    workerDash: {
      label: "Mis trabajos", welcome: "Hola,",
      myApplications: "Mis solicitudes", browseJobs: "Buscar trabajos",
      noApplications: "Aún no has solicitado.", browseAvailable: "Busca trabajos",
      aiScore: "Puntuación",
      verif: {
        label: "Verificación",
        verified: "Tu ID está verificada",
        flagged: "Verificación falló. Envía de nuevo.",
        manualReview: "Alguien está verificando tu ID",
        inProgress: "Verificando tu ID",
        notVerified: "Sin verificar. Verifica para desbloquear trabajos.",
        verifyNow: "Verificar ahora", resubmit: "Enviar de nuevo",
      },
      appStatuses: { pending: "Nuevo", reviewed: "Visto", accepted: "Sí", rejected: "No" },
    },
    browseJobs: {
      label: "Buscar", title: "Trabajos disponibles",
      searchPlaceholder: "Busca trabajo, restaurante o lugar",
      noJobs: "Sin trabajos ahora. Vuelve pronto.",
      noMatch: "Sin trabajos que coincidan.",
      applyNow: "Solicitar",
      loading: "Cargando…",
    },
    applyPage: {
      back: "← Atrás", label: "Solicitar",
      jobDetails: "Info del trabajo", yourApplication: "Tu solicitud",
      pay: "Pago", hours: "Horas", location: "Lugar",
      experienceRequired: "Experiencia necesaria", langPref: "Idioma",
      notSpecified: "No establecido", none: "Ninguno", any: "Cualquiera",
      description: "Sobre el trabajo",
      coverLetter: "Tu mensaje",
      coverLetterPlaceholder: "Cuéntales por qué eres bueno para esto. Simple y honesto.",
      coverLetterNote: "IA puntuará tu solicitud según qué tan bien encajas.",
      submit: "Enviar", submitting: "Enviando…", cancel: "Cancelar",
      jobNotFound: "Trabajo no encontrado o ya no abierto.",
    },
    verifyPage: {
      label: "Trabajador", title: "Verifica tu ID",
      tagline: "Gente verificada consigue más ofertas.",
      stepOf: "Paso", of: "de",
      step1: {
        title: "Envía tu ID",
        desc: "Foto clara de tu ID (pasaporte, licencia, ID nacional).",
        label: "Foto de ID", hint: "JPG o PNG, 10MB máximo", uploading: "Enviando…",
      },
      step2: {
        title: "Toma una selfie",
        desc: "Foto clara de tu cara. IA la comparará con tu ID.",
        label: "Selfie", hint: "JPG o PNG, cara clara", uploading: "Verificando…",
      },
      upload: { clickOrDrag: "Click o arrastra para subir", uploading: "Subiendo…", selected: "Archivo listo. Click para cambiar." },
      result: {
        verified: "Verificado", flagged: "Falló",
        manualReview: "Alguien lo está revisando", pending: "Verificando",
        underReview: "En revisión",
        nameOnId: "Nombre en ID", faceMatchScore: "Cara",
        ageVerified: "Edad OK", ageYes: "Sí (18+)", ageNo: "No / Desconocido",
        resubmit: "Enviar de nuevo", resetting: "Empezando de nuevo…",
      },
      loading: "Cargando…",
    },
  },

  zh: {
    nav: {
      platform: "平台", howItWorks: "使用流程", pricing: "定价",
      login: "登录", getStarted: "立即开始",
    },
    hero: {
      badge: "AI 招聘帮手",
      headline1: "招聘你真正", headline2: "可以信任的", trust: "员工。",
      subtext: "为移民餐厅老板打造。已验证的工人。无需猜测。",
      ctaPost: "发布职位", ctaFind: "找工作",
    },
    metrics: {
      languages: { value: "6 种语言", label: "支持", desc: "用西班牙语、普通话、法语、葡萄牙语、越南语和英语发布招聘。" },
      aiVerified: { value: "已验证", label: "的工人", desc: "每个人都经过验证，在你看到前会获得匹配分数。" },
      jobPost: { value: "60 秒", label: "发布", desc: "用任何语言描述。AI 在一分钟内做好你的广告。" },
    },
    features: {
      sectionLabel: "为何选择 ENTR", sectionHeading: "为餐厅的招聘方式而生。",
      aiScreening: { label: "AI 搜索", heading: "先看最佳人选。", body: "每个申请都得分。最合适的出现在最前面，不是最新的。", chips: [] },
      languages: { label: "6 种语言", heading: "无语言障碍。", body: "人用他们的语言申请。你用你的读。简单。清楚。", chips: ["English","Español","中文","Français","Português","Tiếng Việt"] },
      verification: { label: "验证工人", heading: "知道你在雇谁。", body: "我们检查 ID 和脸。你知道谁走进你的门。", checks: [] },
      cards: {
        aiScreening: {
          header: "申请人", badge: "AI 排名",
          footer: "显示 18 人中的 3", viewAll: "看更多 →",
          candidates: [
            { name: "Maria G.",   role: "线厨 · 3 年", score: 87 },
            { name: "Carlos R.",  role: "备菜 · 1 年",  score: 64 },
            { name: "Jae-won L.", role: "线厨 · 6 月", score: 31 },
          ],
        },
        language: {
          header: "职位语言", subheader: "选择语言看看",
          previewLabel: "中文 例子",
          previewText: "招聘经验丰富的炒锅厨师，负责晚间服务。每周发薪，提供餐饮福利。",
          autoTranslated: "从英文翻译",
        },
        verification: {
          header: "验证", badge: "已验证",
          workerName: "Anh Tran", workerRole: "服务员 · 胡志明市",
          identityVerified: "已验证",
          checks: ["真实 ID", "脸匹配 97%", "有效至 2028"],
        },
      },
    },
    howItWorks: {
      label: "怎么用", heading: "三步招聘。",
      steps: [
        { number: "01", heading: "发布职位", body: "告诉我们职位、薪资、工时。约 60 秒。" },
        { number: "02", heading: "人申请", body: "好人用他们的语言申请。" },
        { number: "03", heading: "AI 匹配", body: "每个申请都被评分和检查。" },
      ],
      cta: "免费开始",
    },
    pricing: {
      label: "价格",
      heading: "简单的价格。",
      subtext: "免费开始。随着增长付费。无惊喜。",
      badge: "最受欢迎",
      plans: [
        {
          name: "免费",
          price: "$0",
          features: [
            { text: "1 个职位", included: true },
            { text: "6 种语言", included: true },
            { text: "看谁申请", included: true },
            { text: "匹配分数", included: false },
            { text: "验证工人", included: false },
            { text: "快速帮助", included: false },
            { text: "报告", included: false },
          ],
          cta: "免费开始",
        },
        {
          name: "初级",
          price: "$19",
          features: [
            { text: "3 个职位", included: true },
            { text: "6 种语言", included: true },
            { text: "匹配分数", included: true },
            { text: "看谁申请", included: true },
            { text: "验证工人", included: true },
            { text: "快速帮助", included: false },
            { text: "报告", included: false },
          ],
          cta: "开始",
        },
        {
          name: "专业",
          price: "$39",
          features: [
            { text: "无限职位", included: true },
            { text: "6 种语言", included: true },
            { text: "匹配分数", included: true },
            { text: "完整验证", included: true },
            { text: "快速帮助", included: true },
            { text: "看谁申请", included: true },
            { text: "报告", included: false },
          ],
          cta: "开始专业",
        },
        {
          name: "商业",
          price: "$79",
          features: [
            { text: "专业的一切", included: true },
            { text: "多家餐厅", included: true },
            { text: "团队使用", included: true },
            { text: "报告", included: true },
            { text: "6 种语言", included: true },
            { text: "完整验证", included: true },
            { text: "快速帮助", included: true },
          ],
          cta: "联系销售",
        },
      ],
      perMonth: "/月",
    },
    featureExplanations: {
      title: "每个计划是什么",
      subtitle: "看每个功能做什么及怎样帮助你",
      features: {
        "1 active listing": {
          heading: "1 个职位",
          description: "一次发布一个。好用来填一个位置。关闭后发布新的。",
          isPaidFeature: false,
        },
        "3 active listings": {
          heading: "3 个职位",
          description: "同时 3 个。适合忙的餐厅。",
          isPaidFeature: false,
        },
        "Unlimited listings": {
          heading: "无限职位",
          description: "想发多少就多少。随时发。",
          isPaidFeature: false,
        },
        "All 6 languages": {
          heading: "6 种语言",
          description: "用英文、西班牙文、普通话、法文、葡文或越文。人用他们的语言申请。你看翻译。",
          isPaidFeature: false,
        },
        "Fit scores": {
          heading: "匹配分数",
          description: "AI 读每个申请打分 0 到 100。最好的在前面。不要读坏的了。节省时间。",
          isPaidFeature: true,
        },
        "Basic applicant list": {
          heading: "看谁申请",
          description: "简单列表。名字、电话、信息。容易打电话或发短信。",
          isPaidFeature: false,
        },
        "Worker verification": {
          heading: "验证工人",
          description: "他们送 ID 和自拍。AI 检查。你看徽章。相信招聘。",
          isPaidFeature: true,
        },
        "Full verification reports": {
          heading: "完整验证",
          description: "所有细节。脸分数、年龄、ID 真假。知道关于工人的一切。",
          isPaidFeature: true,
        },
        "Priority support": {
          heading: "快速帮助",
          description: "快速回答。不是几天。几小时。招聘继续。",
          isPaidFeature: true,
        },
        "Analytics dashboard": {
          heading: "报告",
          description: "图表和数字。什么工作有兴趣。多少人申请。趋势。更聪明决定。",
          isPaidFeature: true,
        },
        "Multiple locations": {
          heading: "多家餐厅",
          description: "很多餐厅。一个地方看。一个登录。容易切换。",
          isPaidFeature: true,
        },
        "Team access": {
          heading: "团队使用",
          description: "经理和员工帮招聘。一个系统。没有多个账号。没有转发信息。",
          isPaidFeature: true,
        },
        "Everything in Pro": {
          heading: "专业的一切",
          description: "商业有专业的全部：无限、分数、验证、帮助、报告。加多家和团队。",
          isPaidFeature: false,
        },
      },
    },
    tech: {
      label: "用的是",
      items: [
        { name: "Claude IA", desc: "匹配与翻译" },
        { name: "React",     desc: "界面" },
        { name: "Flask",     desc: "后端" },
        { name: "PostgreSQL",desc: "数据库" },
        { name: "AWS",       desc: "服务器" },
        { name: "Stripe",    desc: "付费" },
      ],
    },
    chat: {
      title: "ENTR 帮助", subtitle: "问任何东西",
      placeholder: "问一个问题…",
      welcome: "你好。我帮你招人。工作、语言、钱的问题？问我。",
      suggestions: ["怎么匹配的？", "什么语言？", "多少钱？"],
      responses: {
        screening: "AI 读申请打分 0 到 100。最好先出现。不要滚过坏的。",
        languages: "我们支持英文、西班牙文、普通话、法文、葡文、越文。人用他们的语言。你看翻译。",
        pricing: "免费 1 个职位。大多数人选专业 $39 月。无限工作、匹配、验证。",
        default: "ENTR 帮你快速找好人。检查 ID、匹配工作、翻译一切。要知道什么？",
      },
    },
    footer: {
      tagline: "为移民餐厅老板做的简单招聘。",
      columns: { product: "产品", support: "帮助", company: "公司", languages: "语言" },
    },

    // ── Authenticated UI ───────────────────────────────────────────────────────
    layout: {
      dashboard: "面板", postJob: "发布", browseJobs: "找工作",
      verification: "验证", logout: "退出",
      langToggle: "EN",
    },
    auth: {
      welcomeBack: "欢迎回来", signInTitle: "登录",
      email: "邮箱", password: "密码",
      signIn: "登录", signingIn: "中…",
      noAccount: "没有账号？", signUpLink: "注册",
      getStartedFree: "免费开始", createAccountTitle: "创建账号",
      iAmA: "我是…", restaurantOwner: "餐厅老板", jobSeeker: "找工作",
      fullName: "你的名字", restaurantName: "餐厅名",
      preferredLanguage: "语言",
      createAccount: "创建", creatingAccount: "中…",
      alreadyHaveAccount: "有账号？", signInLink: "登录",
    },
    employerDash: {
      label: "我的餐厅", welcome: "欢迎，",
      totalJobs: "工作总数", activeJobs: "现在招聘", totalApplications: "申请总数",
      yourJobPostings: "我的工作", postJob: "+ 发布",
      noJobsYet: "没发布。", postFirstJob: "发布第一个",
      loading: "加载…",
      cols: { title: "工作", location: "地点", pay: "钱", applications: "人数", status: "状态", actions: "行动" },
      open: "招", closed: "关",
      viewApps: "看谁申请", close: "关闭", reopen: "开",
    },
    postJob: {
      label: "老板", title: "发布工作", subtitle: "告诉我们工作，我们发布。",
      titleField: "工作", titlePlaceholder: "线厨、服务、洗碗",
      description: "细节", descPlaceholder: "要做什么？特别的？",
      pay: "钱", payPlaceholder: "$18/小时或 $45k/年",
      hours: "小时", hoursPlaceholder: "全职，30-40 小时一周",
      experience: "工作年数",
      langPref: "语言", langAny: "任何",
      location: "地点", locationPlaceholder: "城市，州",
      submit: "发布", submitting: "中…", cancel: "取消",
    },
    applications: {
      backToDash: "← 返回", label: "谁申请",
      sortedByScore: "最好的先",
      application: "人", applicationPlural: "人",
      noApplications: "没有。",
      aiSummary: "AI 总结", coverLetter: "他们说",
      experience: "经验", languages: "语言", faceMatch: "脸",
      notScored: "没分",
      statuses: { pending: "新", reviewed: "看过", accepted: "是", rejected: "不" },
      verif: { verified: "查证", flagged: "问题", pending: "查中" },
    },
    workerDash: {
      label: "我的工作", welcome: "你好，",
      myApplications: "我的申请", browseJobs: "找工作",
      noApplications: "还没申请。", browseAvailable: "找工作",
      aiScore: "分数",
      verif: {
        label: "验证",
        verified: "你的 ID 查证了",
        flagged: "查证失败。再送。",
        manualReview: "有人在查",
        inProgress: "查中",
        notVerified: "没查。查来打开工作。",
        verifyNow: "查我的 ID", resubmit: "再送",
      },
      appStatuses: { pending: "新", reviewed: "看过", accepted: "是", rejected: "不" },
    },
    browseJobs: {
      label: "找", title: "工作",
      searchPlaceholder: "工作、餐厅或地点",
      noJobs: "现在没有。回来看。",
      noMatch: "没有匹配。",
      applyNow: "申请",
      loading: "加载…",
    },
    applyPage: {
      back: "← 返回", label: "申请",
      jobDetails: "工作信息", yourApplication: "你的申请",
      pay: "钱", hours: "小时", location: "哪",
      experienceRequired: "需要年数", langPref: "语言",
      notSpecified: "没设", none: "无", any: "任何",
      description: "关于工作",
      coverLetter: "你说",
      coverLetterPlaceholder: "告诉他们为什么你好。简单诚实。",
      coverLetterNote: "AI 打分看你有多匹配。",
      submit: "送", submitting: "中…", cancel: "取消",
      jobNotFound: "没有或关了。",
    },
    verifyPage: {
      label: "工人", title: "验证你的 ID",
      tagline: "查证的人得更多工作。",
      stepOf: "步", of: "的",
      step1: {
        title: "送你的 ID",
        desc: "清楚的 ID 照（护照、执照、身份证）。",
        label: "ID", hint: "JPG 或 PNG，10MB 最大", uploading: "中…",
      },
      step2: {
        title: "自拍",
        desc: "清楚的脸。AI 对比 ID。",
        label: "自拍", hint: "JPG 或 PNG，清脸", uploading: "查中…",
      },
      upload: { clickOrDrag: "点或拖来送", uploading: "中…", selected: "预备。点来换。" },
      result: {
        verified: "查证了", flagged: "失败",
        manualReview: "有人看", pending: "查中",
        underReview: "看中",
        nameOnId: "ID 上名", faceMatchScore: "脸",
        ageVerified: "年龄", ageYes: "是（18+）", ageNo: "不 / 不知道",
        resubmit: "再送", resetting: "开始…",
      },
      loading: "加载…",
    },
  },

  fr: {
    nav: {
      platform: "Plateforme", howItWorks: "Comment ça marche", pricing: "Tarifs",
      login: "Se connecter", getStarted: "Commencer",
    },
    hero: {
      badge: "Embauche avec l'IA",
      headline1: "Embauchez des gens", headline2: "en qui vous pouvez", trust: "confiance.",
      subtext: "Pour les propriétaires de restaurants immigrants. Travailleurs vérifiés. Simple.",
      ctaPost: "Publier un emploi", ctaFind: "Trouver du travail",
    },
    metrics: {
      languages: { value: "6 langues", label: "Parlées", desc: "Publiez en espagnol, mandarin, français, portugais, vietnamien et anglais." },
      aiVerified: { value: "Travailleurs", label: "Vérifiés", desc: "Chacun vérifié et noté avant que vous le voyiez." },
      jobPost: { value: "60 secondes", label: "Pour publier", desc: "Décrivez le travail dans n'importe quelle langue. L'IA fait votre annonce en une minute." },
    },
    features: {
      sectionLabel: "Pourquoi ENTR", sectionHeading: "Fait pour comment les restaurants embauchent.",
      aiScreening: { label: "Sélection IA", heading: "Voyez les meilleurs d'abord.", body: "Chaque demande obtient un score. Les meilleurs apparaissent en premier.", chips: [] },
      languages: { label: "6 langues", heading: "Pas de barrière linguistique.", body: "Les gens postulent dans leur langue. Vous le lisez dans la vôtre. Simple.", chips: ["English","Español","中文","Français","Português","Tiếng Việt"] },
      verification: { label: "Vérification", heading: "Sachez qui vous embauchez.", body: "Nous vérifions l'ID et les visages. Vous savez qui entre.", checks: [] },
      cards: {
        aiScreening: {
          header: "Candidats", badge: "Classé par IA",
          footer: "3 de 18 affichés", viewAll: "Voir plus →",
          candidates: [
            { name: "Maria G.",   role: "Cuisinier · 3 ans", score: 87 },
            { name: "Carlos R.",  role: "Aide cuisinier · 1 an",  score: 64 },
            { name: "Jae-won L.", role: "Cuisinier · 6 mois", score: 31 },
          ],
        },
        language: {
          header: "Langue de l'emploi", subheader: "Choisissez une langue à voir",
          previewLabel: "Français Exemple",
          previewText: "Nous cherchons un cuisinier grillardin expérimenté pour le quart du soir.",
          autoTranslated: "Traduit de l'anglais",
        },
        verification: {
          header: "Vérification", badge: "Vérifié",
          workerName: "Anh Tran", workerRole: "Serveur · Ho Chi Minh",
          identityVerified: "Vérifié",
          checks: ["Vrai ID", "Visage 97%", "Valide jusqu'à 2028"],
        },
      },
    },
    howItWorks: {
      label: "Comment ça marche", heading: "Embauchez en trois étapes.",
      steps: [
        { number: "01", heading: "Publiez un emploi", body: "Dites-nous le travail, le salaire, les heures. Environ 60 secondes." },
        { number: "02", heading: "Les gens postulent", body: "Les bons candidats postulent dans leur langue." },
        { number: "03", heading: "L'IA les classe", body: "Chaque demande est notée et vérifiée avant que vous la voyiez." },
      ],
      cta: "Commencer gratuitement",
    },
    pricing: {
      label: "Tarifs",
      heading: "Tarification simple.",
      subtext: "Commencez gratuitement. Payez en grandissant. Pas de surprises.",
      badge: "Plus populaire",
      plans: [
        { name: "Gratuit", price: "$0", features: [
          { text: "1 emploi", included: true },
          { text: "6 langues", included: true },
          { text: "Voir les candidats", included: true },
          { text: "Scores de compatibilité", included: false },
          { text: "Vérification", included: false },
          { text: "Aide rapide", included: false },
          { text: "Rapports", included: false },
        ], cta: "Commencer gratuitement" },
        { name: "Démarrage", price: "$19", features: [
          { text: "3 emplois", included: true },
          { text: "6 langues", included: true },
          { text: "Scores de compatibilité", included: true },
          { text: "Voir les candidats", included: true },
          { text: "Vérification", included: true },
          { text: "Aide rapide", included: false },
          { text: "Rapports", included: false },
        ], cta: "Commencer" },
        { name: "Pro", price: "$39", features: [
          { text: "Emplois illimités", included: true },
          { text: "6 langues", included: true },
          { text: "Scores de compatibilité", included: true },
          { text: "Vérification complète", included: true },
          { text: "Aide rapide", included: true },
          { text: "Voir les candidats", included: true },
          { text: "Rapports", included: false },
        ], cta: "Commencer Pro" },
        { name: "Entreprise", price: "$79", features: [
          { text: "Tout en Pro", included: true },
          { text: "Plusieurs restaurants", included: true },
          { text: "Accès à l'équipe", included: true },
          { text: "Rapports", included: true },
          { text: "6 langues", included: true },
          { text: "Vérification complète", included: true },
          { text: "Aide rapide", included: true },
        ], cta: "Contacter les ventes" },
      ],
      perMonth: "/mois",
    },
    featureExplanations: {
      title: "Qu'est-ce qui est dans chaque plan",
      subtitle: "Voyez ce que fait chaque fonction et comment ça aide",
      features: {
        "1 active listing": { heading: "1 emploi", description: "Un emploi à la fois. Bon pour un poste. Publiez un nouveau quand il est fermé.", isPaidFeature: false },
        "3 active listings": { heading: "3 emplois", description: "3 à la fois. Bon pour les restaurants occupés.", isPaidFeature: false },
        "Unlimited listings": { heading: "Emplois illimités", description: "Autant que vous voulez. Quand vous voulez.", isPaidFeature: false },
        "All 6 languages": { heading: "6 langues", description: "Publiez dans n'importe quelle langue. Les gens postulent dans la leur. Vous voyez tout traduit.", isPaidFeature: false },
        "Fit scores": { heading: "Scores de compatibilité", description: "L'IA lit chaque demande et la note 0 à 100. Les meilleurs en premier. Pas de mauvais à lire.", isPaidFeature: true },
        "Basic applicant list": { heading: "Voir les candidats", description: "Liste simple. Noms, téléphones, messages. Facile d'appeler ou de texte.", isPaidFeature: false },
        "Worker verification": { heading: "Vérification", description: "Ils envoient l'ID et un selfie. L'IA vérifie. Vous voyez un badge. Embauchez en confiance.", isPaidFeature: true },
        "Full verification reports": { heading: "Vérification complète", description: "Tous les détails. Score de visage, âge, ID vrai ou faux. Vous savez tout.", isPaidFeature: true },
        "Priority support": { heading: "Aide rapide", description: "Réponses vites. Pas de jours. Des heures. Votre embauche continue.", isPaidFeature: true },
        "Analytics dashboard": { heading: "Rapports", description: "Graphiques montrant quels emplois intéressent. Combien postulent. Tendances. Décisions plus intelligentes.", isPaidFeature: true },
        "Multiple locations": { heading: "Plusieurs restaurants", description: "Beaucoup de restaurants. Un seul endroit pour voir. Une seule connexion. Facile de changer.", isPaidFeature: true },
        "Team access": { heading: "Accès à l'équipe", description: "Vos gérants et staff aident. Un système. Pas de comptes multiples. Pas de transferts.", isPaidFeature: true },
        "Everything in Pro": { heading: "Tout en Pro", description: "Entreprise a tout en Pro: emplois illimités, scores, vérification, aide, rapports. Plus plusieurs restaurants et équipe.", isPaidFeature: false },
      },
    },
    tech: { label: "Construit avec", items: [
      { name: "Claude IA", desc: "Appariement et traduction" },
      { name: "React", desc: "Interface" },
      { name: "Flask", desc: "Backend" },
      { name: "PostgreSQL", desc: "Base de données" },
      { name: "AWS", desc: "Serveurs" },
      { name: "Stripe", desc: "Paiements" },
    ]},
    chat: {
      title: "Aide ENTR", subtitle: "Posez une question",
      placeholder: "Posez une question…",
      welcome: "Bonjour. Je vous aide à embaucher. Questions sur les emplois, les langues, les tarifs? Demandez-moi.",
      suggestions: ["Comment fonctionne l'appariement?", "Quelles langues?", "Combien ça coûte?"],
      responses: {
        screening: "L'IA lit chaque demande et la note 0 à 100. Les meilleurs en premier. Pas de mauvaises à lire.",
        languages: "Nous soutenons anglais, espagnol, mandarin, français, portugais, vietnamien. Les gens postulent dans leur langue. Vous voyez la traduction.",
        pricing: "Gratuit avec 1 emploi. La plupart choisissent Pro pour $39/mois. Emplois illimités, appariement, vérification.",
        default: "ENTR vous aide à trouver et embaucher de bons travailleurs vite. Nous vérifions l'ID, les appareillons, traduisons tout. Quoi voulez-vous savoir?",
      },
    },
    footer: {
      tagline: "Embauche IA simple pour les propriétaires de restaurants immigrants.",
      columns: { product: "Produit", support: "Aide", company: "À propos", languages: "Langues" },
    },
    layout: {
      dashboard: "Tableau", postJob: "Publier", browseJobs: "Chercher",
      verification: "Vérification", logout: "Déconnexion",
      langToggle: "EN",
    },
    auth: {
      welcomeBack: "Bienvenue", signInTitle: "Se connecter",
      email: "Email", password: "Mot de passe",
      signIn: "Se connecter", signingIn: "Connexion…",
      noAccount: "Pas de compte?", signUpLink: "S'inscrire",
      getStartedFree: "Commencer gratuitement", createAccountTitle: "Créer un compte",
      iAmA: "Je suis…", restaurantOwner: "Propriétaire de restaurant", jobSeeker: "Chercheur d'emploi",
      fullName: "Votre nom", restaurantName: "Nom du restaurant",
      preferredLanguage: "Langue préférée",
      createAccount: "Créer", creatingAccount: "Création…",
      alreadyHaveAccount: "Avez un compte?", signInLink: "Se connecter",
    },
    employerDash: {
      label: "Mon restaurant", welcome: "Bienvenue,",
      totalJobs: "Total emplois", activeJobs: "Actifs", totalApplications: "Total candidatures",
      yourJobPostings: "Mes emplois", postJob: "+ Publier",
      noJobsYet: "Aucun emploi publié.", postFirstJob: "Publiez votre premier",
      loading: "Chargement…",
      cols: { title: "Emploi", location: "Lieu", pay: "Salaire", applications: "Candidats", status: "État", actions: "Action" },
      open: "Ouvert", closed: "Fermé",
      viewApps: "Voir candidats", close: "Fermer", reopen: "Rouvrir",
    },
    postJob: {
      label: "Propriétaire", title: "Publier un emploi", subtitle: "Dites-nous et nous le publions.",
      titleField: "Poste", titlePlaceholder: "Cuisinier, serveur, plongeur",
      description: "Détails", descPlaceholder: "Qu'allez-ils faire? Quelque chose de spécial?",
      pay: "Salaire", payPlaceholder: "$18/h ou $45k/an",
      hours: "Heures", hoursPlaceholder: "Temps plein, 30-40 heures/semaine",
      experience: "Années d'expérience",
      langPref: "Langue", langAny: "N'importe quelle langue",
      location: "Lieu", locationPlaceholder: "Ville, État",
      submit: "Publier", submitting: "Publication…", cancel: "Annuler",
    },
    applications: {
      backToDash: "← Retour", label: "Qui a postulé",
      sortedByScore: "meilleurs en premier",
      application: "personne", applicationPlural: "personnes",
      noApplications: "Aucune candidature.",
      aiSummary: "Résumé IA", coverLetter: "Leur message",
      experience: "Expérience", languages: "Langues", faceMatch: "Visage",
      notScored: "Non noté",
      statuses: { pending: "Nouveau", reviewed: "Vu", accepted: "Oui", rejected: "Non" },
      verif: { verified: "Vérifié", flagged: "Problème", pending: "Vérification" },
    },
    workerDash: {
      label: "Mes emplois", welcome: "Bonjour,",
      myApplications: "Mes candidatures", browseJobs: "Chercher emplois",
      noApplications: "Vous n'avez rien postulé.", browseAvailable: "Chercher emplois",
      aiScore: "Score",
      verif: {
        label: "Vérification",
        verified: "Votre ID est vérifié",
        flagged: "Vérification échouée. Renvoyez.",
        manualReview: "Quelqu'un l'examine",
        inProgress: "Vérification en cours",
        notVerified: "Non vérifié. Vérifiez pour débloquer emplois.",
        verifyNow: "Vérifier maintenant", resubmit: "Renvoyer",
      },
      appStatuses: { pending: "Nouveau", reviewed: "Vu", accepted: "Oui", rejected: "Non" },
    },
    browseJobs: {
      label: "Chercher", title: "Emplois disponibles",
      searchPlaceholder: "Chercher emploi, restaurant ou lieu",
      noJobs: "Pas d'emplois maintenant. Revenez bientôt.",
      noMatch: "Aucun emploi ne correspond.",
      applyNow: "Postuler",
      loading: "Chargement…",
    },
    applyPage: {
      back: "← Retour", label: "Postuler",
      jobDetails: "Détails emploi", yourApplication: "Votre candidature",
      pay: "Salaire", hours: "Heures", location: "Où",
      experienceRequired: "Expérience requise", langPref: "Langue",
      notSpecified: "Non spécifié", none: "Aucun", any: "N'importe quel",
      description: "À propos de l'emploi",
      coverLetter: "Votre message",
      coverLetterPlaceholder: "Dites-leur pourquoi vous êtes bon. Simple et honnête.",
      coverLetterNote: "L'IA notera à quel point vous correspondez.",
      submit: "Envoyer", submitting: "Envoi…", cancel: "Annuler",
      jobNotFound: "Emploi non trouvé ou fermé.",
    },
    verifyPage: {
      label: "Travailleur", title: "Vérifiez votre ID",
      tagline: "Les gens vérifiés obtiennent plus d'offres.",
      stepOf: "Étape", of: "de",
      step1: {
        title: "Envoyez votre ID",
        desc: "Photo claire de votre ID (passeport, permis, ID nationale).",
        label: "Photo ID", hint: "JPG ou PNG, max 10MB", uploading: "Envoi…",
      },
      step2: {
        title: "Prenez un selfie",
        desc: "Photo claire de votre visage. L'IA la comparera avec votre ID.",
        label: "Selfie", hint: "JPG ou PNG, visage clair", uploading: "Vérification…",
      },
      upload: { clickOrDrag: "Cliquez ou faites glisser pour envoyer", uploading: "Envoi…", selected: "Fichier prêt. Cliquez pour changer." },
      result: {
        verified: "Vérifié", flagged: "Échoué",
        manualReview: "Quelqu'un l'examine", pending: "Vérification",
        underReview: "En cours d'examen",
        nameOnId: "Nom sur ID", faceMatchScore: "Visage",
        ageVerified: "Âge OK", ageYes: "Oui (18+)", ageNo: "Non / Inconnu",
        resubmit: "Renvoyer", resetting: "Réinitialisation…",
      },
      loading: "Chargement…",
    },
  },

  pt: {
    nav: {
      platform: "Plataforma", howItWorks: "Como funciona", pricing: "Preços",
      login: "Entrar", getStarted: "Começar",
    },
    hero: {
      badge: "Contratação com IA",
      headline1: "Contrate pessoas", headline2: "em quem pode", trust: "confiar.",
      subtext: "Para donos de restaurantes imigrantes. Trabalhadores verificados. Simples.",
      ctaPost: "Publicar trabalho", ctaFind: "Procurar trabalho",
    },
    metrics: {
      languages: { value: "6 idiomas", label: "Apoiados", desc: "Publique em espanhol, mandarim, francês, português, vietnamita e inglês." },
      aiVerified: { value: "Trabalhadores", label: "Verificados", desc: "Todos verificados e pontuados antes de você ver." },
      jobPost: { value: "60 segundos", label: "Para publicar", desc: "Descreva o trabalho em qualquer idioma. IA faz seu anúncio em um minuto." },
    },
    features: {
      sectionLabel: "Por que ENTR", sectionHeading: "Feito para como restaurantes contratam.",
      aiScreening: { label: "Seleção IA", heading: "Veja os melhores primeiro.", body: "Cada inscrição obtém uma pontuação. O melhor aparece primeiro.", chips: [] },
      languages: { label: "6 idiomas", heading: "Sem barreira de idioma.", body: "Pessoas se inscrevem em seu idioma. Você lê no seu. Simples.", chips: ["English","Español","中文","Français","Português","Tiếng Việt"] },
      verification: { label: "Verificação", heading: "Saiba quem está contratando.", body: "Verificamos ID e faces. Você sabe quem entra.", checks: [] },
      cards: {
        aiScreening: {
          header: "Candidatos", badge: "Classificado por IA",
          footer: "3 de 18 mostrados", viewAll: "Ver mais →",
          candidates: [
            { name: "Maria G.",   role: "Cozinheiro · 3 anos", score: 87 },
            { name: "Carlos R.",  role: "Ajudante · 1 ano",  score: 64 },
            { name: "Jae-won L.", role: "Cozinheiro · 6 meses", score: 31 },
          ],
        },
        language: {
          header: "Idioma do trabalho", subheader: "Escolha um idioma para ver",
          previewLabel: "Português Exemplo",
          previewText: "Procuramos cozinheiro experiente para turno noturno. Pagamento semanal.",
          autoTranslated: "Traduzido do inglês",
        },
        verification: {
          header: "Verificação", badge: "Verificado",
          workerName: "Anh Tran", workerRole: "Garçom · Ho Chi Minh",
          identityVerified: "Verificado",
          checks: ["ID real", "Face 97%", "Válido até 2028"],
        },
      },
    },
    howItWorks: {
      label: "Como funciona", heading: "Contrate em três passos.",
      steps: [
        { number: "01", heading: "Publique um trabalho", body: "Diga-nos o trabalho, salário, horas. Cerca de 60 segundos." },
        { number: "02", heading: "Pessoas se inscrevem", body: "Boas pessoas em seu idioma." },
        { number: "03", heading: "IA classifica", body: "Cada inscrição é pontuada e verificada." },
      ],
      cta: "Começar gratuitamente",
    },
    pricing: {
      label: "Preços",
      heading: "Preços simples.",
      subtext: "Comece grátis. Pague conforme cresce. Sem surpresas.",
      badge: "Mais popular",
      plans: [
        { name: "Grátis", price: "$0", features: [
          { text: "1 trabalho", included: true },
          { text: "6 idiomas", included: true },
          { text: "Ver candidatos", included: true },
          { text: "Pontuações", included: false },
          { text: "Verificação", included: false },
          { text: "Ajuda rápida", included: false },
          { text: "Relatórios", included: false },
        ], cta: "Começar grátis" },
        { name: "Início", price: "$19", features: [
          { text: "3 trabalhos", included: true },
          { text: "6 idiomas", included: true },
          { text: "Pontuações", included: true },
          { text: "Ver candidatos", included: true },
          { text: "Verificação", included: true },
          { text: "Ajuda rápida", included: false },
          { text: "Relatórios", included: false },
        ], cta: "Começar" },
        { name: "Pro", price: "$39", features: [
          { text: "Trabalhos ilimitados", included: true },
          { text: "6 idiomas", included: true },
          { text: "Pontuações", included: true },
          { text: "Verificação completa", included: true },
          { text: "Ajuda rápida", included: true },
          { text: "Ver candidatos", included: true },
          { text: "Relatórios", included: false },
        ], cta: "Começar Pro" },
        { name: "Negócios", price: "$79", features: [
          { text: "Tudo em Pro", included: true },
          { text: "Múltiplos restaurantes", included: true },
          { text: "Acesso à equipe", included: true },
          { text: "Relatórios", included: true },
          { text: "6 idiomas", included: true },
          { text: "Verificação completa", included: true },
          { text: "Ajuda rápida", included: true },
        ], cta: "Fale com vendas" },
      ],
      perMonth: "/mês",
    },
    featureExplanations: {
      title: "O que há em cada plano",
      subtitle: "Veja o que cada função faz e como ajuda",
      features: {
        "1 active listing": { heading: "1 trabalho", description: "Um trabalho por vez. Bom para um cargo. Publique novo quando fechar.", isPaidFeature: false },
        "3 active listings": { heading: "3 trabalhos", description: "3 por vez. Bom para restaurantes ocupados.", isPaidFeature: false },
        "Unlimited listings": { heading: "Trabalhos ilimitados", description: "Quantos quiser. Quando quiser.", isPaidFeature: false },
        "All 6 languages": { heading: "6 idiomas", description: "Publique em qualquer idioma. Pessoas se inscrevem no delas. Você vê tudo traduzido.", isPaidFeature: false },
        "Fit scores": { heading: "Pontuações", description: "IA lê cada inscrição e pontua 0 a 100. Melhores primeiro. Sem ruins para ler.", isPaidFeature: true },
        "Basic applicant list": { heading: "Ver candidatos", description: "Lista simples. Nomes, telefones, mensagens. Fácil ligar ou textar.", isPaidFeature: false },
        "Worker verification": { heading: "Verificação", description: "Enviam ID e selfie. IA verifica. Você vê um badge. Contrate com confiança.", isPaidFeature: true },
        "Full verification reports": { heading: "Verificação completa", description: "Todos os detalhes. Pontuação de face, idade, ID real ou falso. Você sabe tudo.", isPaidFeature: true },
        "Priority support": { heading: "Ajuda rápida", description: "Respostas rápidas. Não dias. Horas. Sua contratação continua.", isPaidFeature: true },
        "Analytics dashboard": { heading: "Relatórios", description: "Gráficos mostrando quais trabalhos interessam. Quantos se inscrevem. Tendências. Decisões melhores.", isPaidFeature: true },
        "Multiple locations": { heading: "Múltiplos restaurantes", description: "Muitos restaurantes. Um lugar para ver. Um login. Fácil mudar.", isPaidFeature: true },
        "Team access": { heading: "Acesso à equipe", description: "Seus gerentes e staff ajudam. Um sistema. Sem contas múltiplas. Sem transferências.", isPaidFeature: true },
        "Everything in Pro": { heading: "Tudo em Pro", description: "Negócios tem tudo em Pro: trabalhos ilimitados, pontuações, verificação, ajuda, relatórios. Mais múltiplos restaurantes e equipe.", isPaidFeature: false },
      },
    },
    tech: { label: "Construído com", items: [
      { name: "Claude IA", desc: "Correspondência e tradução" },
      { name: "React", desc: "Interface" },
      { name: "Flask", desc: "Backend" },
      { name: "PostgreSQL", desc: "Banco de dados" },
      { name: "AWS", desc: "Servidores" },
      { name: "Stripe", desc: "Pagamentos" },
    ]},
    chat: {
      title: "Ajuda ENTR", subtitle: "Faça uma pergunta",
      placeholder: "Faça uma pergunta…",
      welcome: "Oi. Ajudo você a contratar. Perguntas sobre trabalhos, idiomas, preços? Pergunte-me.",
      suggestions: ["Como funciona a correspondência?", "Que idiomas?", "Quanto custa?"],
      responses: {
        screening: "IA lê cada inscrição e pontua 0 a 100. Melhores primeiro. Sem ruins para ler.",
        languages: "Apoiamos inglês, espanhol, mandarim, francês, português, vietnamita. Pessoas se inscrevem no delas. Você vê traduzido.",
        pricing: "Grátis com 1 trabalho. Maioria escolhe Pro por $39/mês. Trabalhos ilimitados, correspondência, verificação.",
        default: "ENTR ajuda você encontrar e contratar boas pessoas rápido. Verificamos ID, correspondemos, traduzimos tudo. O que quer saber?",
      },
    },
    footer: {
      tagline: "Contratação IA simples para donos de restaurantes imigrantes.",
      columns: { product: "Produto", support: "Ajuda", company: "Sobre", languages: "Idiomas" },
    },
    layout: {
      dashboard: "Painel", postJob: "Publicar", browseJobs: "Procurar",
      verification: "Verificação", logout: "Sair",
      langToggle: "EN",
    },
    auth: {
      welcomeBack: "Bem-vindo", signInTitle: "Entrar",
      email: "Email", password: "Senha",
      signIn: "Entrar", signingIn: "Entrando…",
      noAccount: "Sem conta?", signUpLink: "Inscrever",
      getStartedFree: "Começar grátis", createAccountTitle: "Criar conta",
      iAmA: "Sou…", restaurantOwner: "Dono de restaurante", jobSeeker: "Procurando trabalho",
      fullName: "Seu nome", restaurantName: "Nome do restaurante",
      preferredLanguage: "Idioma preferido",
      createAccount: "Criar", creatingAccount: "Criando…",
      alreadyHaveAccount: "Tem conta?", signInLink: "Entrar",
    },
    employerDash: {
      label: "Meu restaurante", welcome: "Bem-vindo,",
      totalJobs: "Total de trabalhos", activeJobs: "Ativos", totalApplications: "Total de inscrições",
      yourJobPostings: "Meus trabalhos", postJob: "+ Publicar",
      noJobsYet: "Nenhum trabalho publicado.", postFirstJob: "Publique seu primeiro",
      loading: "Carregando…",
      cols: { title: "Trabalho", location: "Lugar", pay: "Salário", applications: "Candidatos", status: "Status", actions: "Ação" },
      open: "Aberto", closed: "Fechado",
      viewApps: "Ver candidatos", close: "Fechar", reopen: "Reabrir",
    },
    postJob: {
      label: "Dono", title: "Publicar trabalho", subtitle: "Diga-nos e publicamos.",
      titleField: "Cargo", titlePlaceholder: "Cozinheiro, garçom, lavador",
      description: "Detalhes", descPlaceholder: "O que vão fazer? Algo especial?",
      pay: "Salário", payPlaceholder: "$18/h ou $45k/ano",
      hours: "Horas", hoursPlaceholder: "Tempo integral, 30-40 horas/semana",
      experience: "Anos de experiência",
      langPref: "Idioma", langAny: "Qualquer idioma",
      location: "Lugar", locationPlaceholder: "Cidade, estado",
      submit: "Publicar", submitting: "Publicando…", cancel: "Cancelar",
    },
    applications: {
      backToDash: "← Voltar", label: "Quem se inscreveu",
      sortedByScore: "melhores primeiro",
      application: "pessoa", applicationPlural: "pessoas",
      noApplications: "Nenhuma inscrição.",
      aiSummary: "Resumo IA", coverLetter: "Sua mensagem",
      experience: "Experiência", languages: "Idiomas", faceMatch: "Rosto",
      notScored: "Sem pontuação",
      statuses: { pending: "Novo", reviewed: "Visto", accepted: "Sim", rejected: "Não" },
      verif: { verified: "Verificado", flagged: "Problema", pending: "Verificando" },
    },
    workerDash: {
      label: "Meus trabalhos", welcome: "Oi,",
      myApplications: "Minhas inscrições", browseJobs: "Procurar trabalhos",
      noApplications: "Você não se inscreveu em nada.", browseAvailable: "Procurar trabalhos",
      aiScore: "Pontuação",
      verif: {
        label: "Verificação",
        verified: "Sua ID foi verificada",
        flagged: "Verificação falhou. Envie novamente.",
        manualReview: "Alguém está analisando",
        inProgress: "Verificando",
        notVerified: "Não verificado. Verifique para desbloquear trabalhos.",
        verifyNow: "Verificar agora", resubmit: "Enviar novamente",
      },
      appStatuses: { pending: "Novo", reviewed: "Visto", accepted: "Sim", rejected: "Não" },
    },
    browseJobs: {
      label: "Procurar", title: "Trabalhos disponíveis",
      searchPlaceholder: "Procure trabalho, restaurante ou lugar",
      noJobs: "Sem trabalhos agora. Volte em breve.",
      noMatch: "Nenhum trabalho corresponde.",
      applyNow: "Inscrever",
      loading: "Carregando…",
    },
    applyPage: {
      back: "← Voltar", label: "Inscrever",
      jobDetails: "Detalhes do trabalho", yourApplication: "Sua inscrição",
      pay: "Salário", hours: "Horas", location: "Onde",
      experienceRequired: "Experiência necessária", langPref: "Idioma",
      notSpecified: "Não especificado", none: "Nenhum", any: "Qualquer",
      description: "Sobre o trabalho",
      coverLetter: "Sua mensagem",
      coverLetterPlaceholder: "Diga por que você é bom nisso. Simples e honesto.",
      coverLetterNote: "IA avaliará como você corresponde.",
      submit: "Enviar", submitting: "Enviando…", cancel: "Cancelar",
      jobNotFound: "Trabalho não encontrado ou fechado.",
    },
    verifyPage: {
      label: "Trabalhador", title: "Verifique sua ID",
      tagline: "Pessoas verificadas conseguem mais ofertas.",
      stepOf: "Passo", of: "de",
      step1: {
        title: "Envie sua ID",
        desc: "Foto clara de sua ID (passaporte, carteira, ID nacional).",
        label: "Foto ID", hint: "JPG ou PNG, max 10MB", uploading: "Enviando…",
      },
      step2: {
        title: "Tire um selfie",
        desc: "Foto clara de seu rosto. IA comparará com sua ID.",
        label: "Selfie", hint: "JPG ou PNG, rosto claro", uploading: "Verificando…",
      },
      upload: { clickOrDrag: "Clique ou arraste para enviar", uploading: "Enviando…", selected: "Arquivo pronto. Clique para mudar." },
      result: {
        verified: "Verificado", flagged: "Falhou",
        manualReview: "Alguém está analisando", pending: "Verificando",
        underReview: "Em revisão",
        nameOnId: "Nome na ID", faceMatchScore: "Rosto",
        ageVerified: "Idade OK", ageYes: "Sim (18+)", ageNo: "Não / Desconhecido",
        resubmit: "Enviar novamente", resetting: "Começando novamente…",
      },
      loading: "Carregando…",
    },
  },

  vi: {
    nav: {
      platform: "Nền tảng", howItWorks: "Hoạt động như thế nào", pricing: "Giá",
      login: "Đăng nhập", getStarted: "Bắt đầu",
    },
    hero: {
      badge: "Tuyển dụng AI",
      headline1: "Tuyển dụng những người", headline2: "bạn thực sự có thể", trust: "tin tưởng.",
      subtext: "Cho chủ nhà hàng nhập cư. Công nhân đã xác minh. Đơn giản.",
      ctaPost: "Đăng công việc", ctaFind: "Tìm việc",
    },
    metrics: {
      languages: { value: "6 ngôn ngữ", label: "Hỗ trợ", desc: "Đăng bằng tiếng Tây Ban Nha, Trung Quốc, Pháp, Bồ Đào Nha, Việt Nam và Anh." },
      aiVerified: { value: "Công nhân", label: "Đã xác minh", desc: "Tất cả được xác minh và chấm điểm trước khi bạn thấy." },
      jobPost: { value: "60 giây", label: "Để đăng", desc: "Mô tả công việc bằng bất kỳ ngôn ngữ nào. AI làm quảng cáo của bạn trong một phút." },
    },
    features: {
      sectionLabel: "Tại sao ENTR", sectionHeading: "Được tạo cho cách nhà hàng tuyển dụng.",
      aiScreening: { label: "Lọc AI", heading: "Nhìn thấy những người tốt nhất trước tiên.", body: "Mỗi đơn xin việc được chấm điểm. Những người tốt nhất xuất hiện trước.", chips: [] },
      languages: { label: "6 ngôn ngữ", heading: "Không có rào cản ngôn ngữ.", body: "Người dân nộp đơn bằng ngôn ngữ của họ. Bạn đọc bằng của bạn. Đơn giản.", chips: ["English","Español","中文","Français","Português","Tiếng Việt"] },
      verification: { label: "Xác minh", heading: "Biết bạn đang tuyển dụng ai.", body: "Chúng tôi kiểm tra ID và khuôn mặt. Bạn biết ai đi vào.", checks: [] },
      cards: {
        aiScreening: {
          header: "Ứng viên", badge: "Được phân loại bởi AI",
          footer: "3 của 18 được hiển thị", viewAll: "Xem thêm →",
          candidates: [
            { name: "Maria G.",   role: "Đầu bếp · 3 năm", score: 87 },
            { name: "Carlos R.",  role: "Trợ lý · 1 năm",  score: 64 },
            { name: "Jae-won L.", role: "Đầu bếp · 6 tháng", score: 31 },
          ],
        },
        language: {
          header: "Ngôn ngữ công việc", subheader: "Chọn ngôn ngữ để xem",
          previewLabel: "Ví dụ tiếng Việt",
          previewText: "Tuyển đầu bếp kinh nghiệm cho ca tối. Trả lương hàng tuần.",
          autoTranslated: "Dịch từ tiếng Anh",
        },
        verification: {
          header: "Xác minh", badge: "Đã xác minh",
          workerName: "Anh Tran", workerRole: "Phục vụ · Ho Chi Minh",
          identityVerified: "Đã xác minh",
          checks: ["ID thật", "Khuôn mặt 97%", "Hợp lệ đến 2028"],
        },
      },
    },
    howItWorks: {
      label: "Hoạt động như thế nào", heading: "Tuyển dụng trong ba bước.",
      steps: [
        { number: "01", heading: "Đăng công việc", body: "Cho chúng tôi biết công việc, lương, giờ. Khoảng 60 giây." },
        { number: "02", heading: "Người nộp đơn", body: "Những người tốt bằng ngôn ngữ của họ." },
        { number: "03", heading: "AI xếp hạng", body: "Mỗi đơn được chấm điểm và xác minh." },
      ],
      cta: "Bắt đầu miễn phí",
    },
    pricing: {
      label: "Giá",
      heading: "Giá đơn giản.",
      subtext: "Bắt đầu miễn phí. Trả tiền khi phát triển. Không bất ngờ.",
      badge: "Phổ biến nhất",
      plans: [
        { name: "Miễn phí", price: "$0", features: [
          { text: "1 công việc", included: true },
          { text: "6 ngôn ngữ", included: true },
          { text: "Xem ứng viên", included: true },
          { text: "Điểm phù hợp", included: false },
          { text: "Xác minh", included: false },
          { text: "Hỗ trợ nhanh", included: false },
          { text: "Báo cáo", included: false },
        ], cta: "Bắt đầu miễn phí" },
        { name: "Khởi động", price: "$19", features: [
          { text: "3 công việc", included: true },
          { text: "6 ngôn ngữ", included: true },
          { text: "Điểm phù hợp", included: true },
          { text: "Xem ứng viên", included: true },
          { text: "Xác minh", included: true },
          { text: "Hỗ trợ nhanh", included: false },
          { text: "Báo cáo", included: false },
        ], cta: "Bắt đầu" },
        { name: "Pro", price: "$39", features: [
          { text: "Công việc không giới hạn", included: true },
          { text: "6 ngôn ngữ", included: true },
          { text: "Điểm phù hợp", included: true },
          { text: "Xác minh đầy đủ", included: true },
          { text: "Hỗ trợ nhanh", included: true },
          { text: "Xem ứng viên", included: true },
          { text: "Báo cáo", included: false },
        ], cta: "Bắt đầu Pro" },
        { name: "Doanh nghiệp", price: "$79", features: [
          { text: "Tất cả trong Pro", included: true },
          { text: "Nhiều nhà hàng", included: true },
          { text: "Truy cập nhóm", included: true },
          { text: "Báo cáo", included: true },
          { text: "6 ngôn ngữ", included: true },
          { text: "Xác minh đầy đủ", included: true },
          { text: "Hỗ trợ nhanh", included: true },
        ], cta: "Liên hệ bán hàng" },
      ],
      perMonth: "/tháng",
    },
    featureExplanations: {
      title: "Cái gì trong mỗi kế hoạch",
      subtitle: "Xem mỗi tính năng làm gì và cách nó giúp",
      features: {
        "1 active listing": { heading: "1 công việc", description: "Một công việc một lúc. Tốt cho một vị trí. Đăng cái mới khi đóng.", isPaidFeature: false },
        "3 active listings": { heading: "3 công việc", description: "3 lúc một. Tốt cho nhà hàng bận rộn.", isPaidFeature: false },
        "Unlimited listings": { heading: "Công việc không giới hạn", description: "Bao nhiêu bạn muốn. Khi nào bạn muốn.", isPaidFeature: false },
        "All 6 languages": { heading: "6 ngôn ngữ", description: "Đăng bằng bất kỳ ngôn ngữ nào. Người nộp bằng của họ. Bạn thấy tất cả dịch.", isPaidFeature: false },
        "Fit scores": { heading: "Điểm phù hợp", description: "AI đọc mỗi đơn và chấm 0 đến 100. Cái tốt nhất trước. Không xấu để đọc.", isPaidFeature: true },
        "Basic applicant list": { heading: "Xem ứng viên", description: "Danh sách đơn giản. Tên, điện thoại, tin nhắn. Dễ gọi hoặc nhắn tin.", isPaidFeature: false },
        "Worker verification": { heading: "Xác minh", description: "Họ gửi ID và selfie. AI kiểm tra. Bạn thấy badge. Tuyển dụng với tự tin.", isPaidFeature: true },
        "Full verification reports": { heading: "Xác minh đầy đủ", description: "Tất cả chi tiết. Điểm khuôn mặt, tuổi, ID thật hay giả. Bạn biết tất cả.", isPaidFeature: true },
        "Priority support": { heading: "Hỗ trợ nhanh", description: "Trả lời nhanh. Không phải ngày. Giờ. Tuyển dụng của bạn tiếp tục.", isPaidFeature: true },
        "Analytics dashboard": { heading: "Báo cáo", description: "Biểu đồ chỉ công việc nào có sở thích. Bao nhiêu nộp đơn. Xu hướng. Quyết định thông minh hơn.", isPaidFeature: true },
        "Multiple locations": { heading: "Nhiều nhà hàng", description: "Nhiều nhà hàng. Một nơi để xem. Một đăng nhập. Dễ dàng thay đổi.", isPaidFeature: true },
        "Team access": { heading: "Truy cập nhóm", description: "Người quản lý và nhân viên của bạn giúp. Một hệ thống. Không có tài khoản nhiều. Không chuyển tiếp.", isPaidFeature: true },
        "Everything in Pro": { heading: "Tất cả trong Pro", description: "Doanh nghiệp có tất cả trong Pro: công việc không giới hạn, điểm, xác minh, hỗ trợ, báo cáo. Cộng nhiều nhà hàng và nhóm.", isPaidFeature: false },
      },
    },
    tech: { label: "Xây dựng bằng", items: [
      { name: "Claude AI", desc: "Ghép nối và dịch" },
      { name: "React", desc: "Giao diện" },
      { name: "Flask", desc: "Backend" },
      { name: "PostgreSQL", desc: "Cơ sở dữ liệu" },
      { name: "AWS", desc: "Máy chủ" },
      { name: "Stripe", desc: "Thanh toán" },
    ]},
    chat: {
      title: "Trợ giúp ENTR", subtitle: "Hỏi cái gì",
      placeholder: "Hỏi một câu hỏi…",
      welcome: "Xin chào. Tôi giúp bạn tuyển dụng. Câu hỏi về công việc, ngôn ngữ, giá? Hỏi tôi.",
      suggestions: ["Ghép nối hoạt động như thế nào?", "Ngôn ngữ nào?", "Giá bao nhiêu?"],
      responses: {
        screening: "AI đọc mỗi đơn và chấm 0 đến 100. Cái tốt nhất trước. Không xấu để đọc.",
        languages: "Chúng tôi hỗ trợ Anh, Tây Ban Nha, Trung Quốc, Pháp, Bồ Đào Nha, Việt Nam. Người nộp bằng của họ. Bạn thấy dịch.",
        pricing: "Miễn phí với 1 công việc. Hầu hết chọn Pro cho $39/tháng. Công việc không giới hạn, ghép nối, xác minh.",
        default: "ENTR giúp bạn tìm và tuyển dụng những người tốt nhanh chóng. Chúng tôi kiểm tra ID, ghép nối, dịch tất cả. Bạn muốn biết cái gì?",
      },
    },
    footer: {
      tagline: "Tuyển dụng AI đơn giản cho chủ nhà hàng nhập cư.",
      columns: { product: "Sản phẩm", support: "Hỗ trợ", company: "Về", languages: "Ngôn ngữ" },
    },
    layout: {
      dashboard: "Bảng", postJob: "Đăng", browseJobs: "Tìm",
      verification: "Xác minh", logout: "Đăng xuất",
      langToggle: "EN",
    },
    auth: {
      welcomeBack: "Chào mừng trở lại", signInTitle: "Đăng nhập",
      email: "Email", password: "Mật khẩu",
      signIn: "Đăng nhập", signingIn: "Đang đăng nhập…",
      noAccount: "Không có tài khoản?", signUpLink: "Đăng ký",
      getStartedFree: "Bắt đầu miễn phí", createAccountTitle: "Tạo tài khoản",
      iAmA: "Tôi là…", restaurantOwner: "Chủ nhà hàng", jobSeeker: "Tìm việc",
      fullName: "Tên của bạn", restaurantName: "Tên nhà hàng",
      preferredLanguage: "Ngôn ngữ ưa thích",
      createAccount: "Tạo", creatingAccount: "Tạo…",
      alreadyHaveAccount: "Có tài khoản?", signInLink: "Đăng nhập",
    },
    employerDash: {
      label: "Nhà hàng của tôi", welcome: "Chào mừng,",
      totalJobs: "Tổng công việc", activeJobs: "Hiện hoạt", totalApplications: "Tổng đơn xin",
      yourJobPostings: "Công việc của tôi", postJob: "+ Đăng",
      noJobsYet: "Không có công việc được đăng.", postFirstJob: "Đăng cái đầu tiên",
      loading: "Đang tải…",
      cols: { title: "Công việc", location: "Nơi", pay: "Lương", applications: "Ứng viên", status: "Tình trạng", actions: "Hành động" },
      open: "Mở", closed: "Đóng",
      viewApps: "Xem ứng viên", close: "Đóng", reopen: "Mở lại",
    },
    postJob: {
      label: "Chủ", title: "Đăng công việc", subtitle: "Cho chúng tôi biết và chúng tôi đăng.",
      titleField: "Chức vụ", titlePlaceholder: "Đầu bếp, phục vụ, rửa bát",
      description: "Chi tiết", descPlaceholder: "Họ sẽ làm gì? Cái gì đặc biệt?",
      pay: "Lương", payPlaceholder: "$18/h hoặc $45k/năm",
      hours: "Giờ", hoursPlaceholder: "Toàn thời gian, 30-40 giờ/tuần",
      experience: "Năm kinh nghiệm",
      langPref: "Ngôn ngữ", langAny: "Bất kỳ ngôn ngữ nào",
      location: "Nơi", locationPlaceholder: "Thành phố, tiểu bang",
      submit: "Đăng", submitting: "Đang đăng…", cancel: "Hủy",
    },
    applications: {
      backToDash: "← Quay lại", label: "Ai nộp đơn",
      sortedByScore: "cái tốt nhất trước",
      application: "người", applicationPlural: "người",
      noApplications: "Không có đơn xin.",
      aiSummary: "Tóm tắt AI", coverLetter: "Thông điệp của họ",
      experience: "Kinh nghiệm", languages: "Ngôn ngữ", faceMatch: "Khuôn mặt",
      notScored: "Chưa chấm",
      statuses: { pending: "Mới", reviewed: "Đã xem", accepted: "Có", rejected: "Không" },
      verif: { verified: "Xác minh", flagged: "Vấn đề", pending: "Xác minh" },
    },
    workerDash: {
      label: "Công việc của tôi", welcome: "Xin chào,",
      myApplications: "Đơn xin của tôi", browseJobs: "Tìm công việc",
      noApplications: "Bạn chưa nộp đơn.", browseAvailable: "Tìm công việc",
      aiScore: "Điểm",
      verif: {
        label: "Xác minh",
        verified: "ID của bạn được xác minh",
        flagged: "Xác minh thất bại. Gửi lại.",
        manualReview: "Ai đó đang xem",
        inProgress: "Xác minh",
        notVerified: "Chưa xác minh. Xác minh để mở khóa công việc.",
        verifyNow: "Xác minh ngay", resubmit: "Gửi lại",
      },
      appStatuses: { pending: "Mới", reviewed: "Đã xem", accepted: "Có", rejected: "Không" },
    },
    browseJobs: {
      label: "Tìm", title: "Công việc có sẵn",
      searchPlaceholder: "Tìm công việc, nhà hàng hoặc nơi",
      noJobs: "Không có công việc bây giờ. Quay lại sớm.",
      noMatch: "Không có công việc phù hợp.",
      applyNow: "Nộp đơn",
      loading: "Đang tải…",
    },
    applyPage: {
      back: "← Quay lại", label: "Nộp đơn",
      jobDetails: "Chi tiết công việc", yourApplication: "Đơn xin của bạn",
      pay: "Lương", hours: "Giờ", location: "Ở đâu",
      experienceRequired: "Kinh nghiệm cần thiết", langPref: "Ngôn ngữ",
      notSpecified: "Không xác định", none: "Không", any: "Bất kỳ",
      description: "Về công việc",
      coverLetter: "Thông điệp của bạn",
      coverLetterPlaceholder: "Cho họ biết tại sao bạn tốt ở cái này. Đơn giản và chân thành.",
      coverLetterNote: "AI sẽ chấm điểm bạn phù hợp như thế nào.",
      submit: "Gửi", submitting: "Đang gửi…", cancel: "Hủy",
      jobNotFound: "Công việc không tìm thấy hoặc đã đóng.",
    },
    verifyPage: {
      label: "Công nhân", title: "Xác minh ID của bạn",
      tagline: "Người được xác minh nhận được nhiều lời mời hơn.",
      stepOf: "Bước", of: "của",
      step1: {
        title: "Gửi ID của bạn",
        desc: "Ảnh rõ ràng của ID của bạn (hộ chiếu, bằng lái xe, ID quốc gia).",
        label: "Ảnh ID", hint: "JPG hoặc PNG, tối đa 10MB", uploading: "Đang gửi…",
      },
      step2: {
        title: "Chụp selfie",
        desc: "Ảnh rõ ràng của khuôn mặt của bạn. AI sẽ so sánh với ID.",
        label: "Selfie", hint: "JPG hoặc PNG, khuôn mặt rõ", uploading: "Xác minh…",
      },
      upload: { clickOrDrag: "Nhấp hoặc kéo để gửi", uploading: "Đang gửi…", selected: "Tập tin sẵn sàng. Nhấp để thay đổi." },
      result: {
        verified: "Xác minh", flagged: "Thất bại",
        manualReview: "Ai đó đang xem", pending: "Xác minh",
        underReview: "Đang xem xét",
        nameOnId: "Tên trên ID", faceMatchScore: "Khuôn mặt",
        ageVerified: "Tuổi OK", ageYes: "Có (18+)", ageNo: "Không / Không biết",
        resubmit: "Gửi lại", resetting: "Bắt đầu lại…",
      },
      loading: "Đang tải…",
    },
  },
};

type Translations = typeof translations.en;

const LanguageContext = createContext<{
  lang: Lang;
  currentLang: Lang;
  dialect: Dialect;
  setLang: (l: Lang) => void;
  setDialect: (d: Dialect) => void;
  t: Translations;
  languageFamilies: typeof LANGUAGE_FAMILIES;
}>({
  lang: "en",
  currentLang: "en",
  dialect: null,
  setLang: () => {},
  setDialect: () => {},
  t: translations.en,
  languageFamilies: LANGUAGE_FAMILIES,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  const [dialect, setDialect] = useState<Dialect>(null);

  return (
    <LanguageContext.Provider
      value={{
        lang,
        currentLang: lang,
        dialect,
        setLang,
        setDialect,
        t: translations[lang],
        languageFamilies: LANGUAGE_FAMILIES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
